#include <iostream>
#include <ctime>
using namespace std;
int main()
{

    int computernum, guess;

    // generate the random number b/t 1 to 100

    srand(time(0));
    // min + ran() %( max- min +1)
    computernum =  rand() % (100 - 1 );

    // cout << "the random number generated by the computer is "
    //      <<  computernum  << endl;
    cout << "type a number b/t 1 to 100"<<endl;
    cout << "can you guess what it is?  Enter your guess" << endl;
    cin >> guess;

    while (guess != computernum)
    {
        if (guess > computernum)

        {

            cout << " your " << guess << " is high , try small number "<< endl;
            
        }
        else
        {
            cout << " your " << guess << " is small , try larger number " << endl;
        }
        cin >> guess;
    }
            cout << "congratulation you got the correct,the number is  " << computernum << endl;
        
    
        return 0;
        
    }